# Generated by Django 5.2.6 on 2025-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('expiry', models.DateField(auto_now_add=True, verbose_name='Due Date')),
                ('priority', models.CharField(choices=[('Critical', '10'), ('High', '8'), ('Medium', '6'), ('Low', '4'), ('Lowest', '2')], default='Lowest', max_length=10)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
