# Generated by Django 5.2.6 on 2025-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_main', '0002_tasks_delete_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('in progress', 'IN PROGRESS'), ('done', 'DONE')], default='pending'),
        ),
    ]
