# Generated by Django 5.2.6 on 2025-09-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_main', '0003_alter_tasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='expiry',
            field=models.DateField(),
        ),
    ]
